"""
Markdown documentation generation module.
Generates human-readable database documentation.
"""

from typing import Dict


def generate_markdown(schema: Dict) -> str:
    """
    Generate comprehensive Markdown documentation from schema.
    
    Args:
        schema: Database schema dictionary
        
    Returns:
        str: Markdown formatted documentation
    """
    md = "# Database Documentation\n\n"
    md += "**Auto-generated by SchemaIntelligence**\n\n"

    for table, info in schema.items():
        md += f"## {table}\n"
        md += f"**Primary Key:** {', '.join(info['primary_key']) if info['primary_key'] else 'None'}\n\n"

        # Columns section
        md += "### Columns\n\n"
        md += "| Name | Type | Nullable |\n"
        md += "|------|------|----------|\n"
        
        for col in info["columns"]:
            nullable = "✓" if col["nullable"] else "✗"
            md += f"| `{col['name']}` | `{col['type']}` | {nullable} |\n"

        # Foreign keys section
        if info["foreign_keys"]:
            md += "\n### Foreign Keys\n\n"
            md += "| Column | References | Type |\n"
            md += "|--------|------------|------|\n"
            
            for fk in info["foreign_keys"]:
                join_type = "LEFT" if fk['nullable'] else "INNER"
                md += (
                    f"| `{fk['column']}` | "
                    f"`{fk['references_table']}({fk['references_column']})` | "
                    f"{join_type} |\n"
                )

        md += "\n---\n\n"

    return md


def generate_table_documentation(table_name: str, table_info: Dict) -> str:
    """
    Generate documentation for a single table.
    
    Args:
        table_name: Name of the table
        table_info: Table information dictionary
        
    Returns:
        str: Markdown documentation for the table
    """
    md = f"# {table_name}\n\n"
    
    if table_info.get("primary_key"):
        md += f"**Primary Key:** `{', '.join(table_info['primary_key'])}`\n\n"
    
    # Columns
    md += "## Columns\n\n"
    for col in table_info.get("columns", []):
        nullable_text = "optional" if col["nullable"] else "required"
        md += f"- **`{col['name']}`** (`{col['type']}`) - {nullable_text}\n"
    
    # Foreign keys
    if table_info.get("foreign_keys"):
        md += "\n## Relationships\n\n"
        for fk in table_info["foreign_keys"]:
            md += (
                f"- `{fk['column']}` → "
                f"`{fk['references_table']}.{fk['references_column']}`\n"
            )
    
    return md
